# Generated by Django 4.2.5 on 2023-10-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email address')),
                ('password', models.CharField()),
                ('is_system_admin', models.BooleanField(default=False)),
                ('is_pro', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('refresh_token', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
