# Generated by Django 4.2.5 on 2023-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20231028_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
    ]
