# Generated by Django 4.2.5 on 2024-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_user_is_pro_alter_user_is_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
