# Generated by Django 4.2.5 on 2024-02-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='SnippetTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snippet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.snippet')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.tag')),
            ],
        ),
    ]
