# Generated by Django 4.2.5 on 2024-02-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_rename_language_id_snippet_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='uuid',
        ),
    ]
