# Generated by Django 4.2.5 on 2024-02-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_rename_user_snippet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='language_id',
        ),
    ]
