# Generated by Django 4.2.5 on 2024-02-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_rename_language_snippet_language_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='snippettag',
            old_name='snippet_id',
            new_name='snippet',
        ),
        migrations.RenameField(
            model_name='snippettag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
