# Generated by Django 4.2.5 on 2024-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0012_rename_user_id_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='untitled', max_length=80),
            preserve_default=False,
        ),
    ]
