# Generated by Django 4.2.5 on 2024-02-23 15:32
import logging
from django.db import migrations, models
logger = logging.getLogger(__name__)


def initial_tag_limit_setting(apps, schema_editor):
    # env = environ.Env()
    KEY = "TAG_LIMIT"
    VALUE = "5"
    Setting = apps.get_model("manager", "Setting")
    if not Setting.objects.filter(key=KEY).exists():
        logger.info("Set initial tag limit")
        setting = Setting.objects.create(
            key=KEY, value=VALUE
        )
        setting.save()
    else:
        logger.info("Tag limit has been initialized")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RunPython(initial_tag_limit_setting)
    ]
